import { Day1Data } from '../../store/useDayStore';

/**
 * Interface representing the scoring outputs generated by Day 1.
 */
export interface Day1ScoringResult {
  connectionScoreContribution: number; // Slider (up to 20) + Vibe Check (up to 10)
  dedicationPointsEarned: number;        // D1 complete = +1.0
  axisASignals: {
    expressive: number;
    active: number;
  };
  axisBSignals: {
    deep: number;
    present: number;
  };
  axisCSignals: {
    protecting: number;
    building: number;
  };
}

/**
 * Day 1 Scoring & Logic Engine
 * Processes Day 1 user answers (Connection Slider, Vibe Check tiles, and Spark Quiz Q1-Q7)
 * to output precise scoring parameters and badge axis signals.
 */
export const Day1Scoring = {
  /**
   * Calculates the full scoring breakdown for Day 1 based on the store's Day 1 data.
   * 
   * @param day1 The stored data for Day 1
   * @returns Day1ScoringResult containing contributions for Connection, Dedication, and the 3 Badge Axes.
   */
  calculate: (day1: Day1Data): Day1ScoringResult => {
    // Initialize results
    let connectionScoreContribution = 0;
    let dedicationPointsEarned = 0;
    
    const axisASignals = { expressive: 0, active: 0 };
    const axisBSignals = { deep: 0, present: 0 };
    const axisCSignals = { protecting: 0, building: 0 };

    // ─────────────────────────────────────────────────────────────
    // 1. Connection Score Contribution (PRD §5.1 & §5.2)
    // ─────────────────────────────────────────────────────────────
    
    // Checkpoint A: Dragged Slider Baseline (Score 1-10) scaled by 2 (Max 20 pts)
    const sliderPts = Math.min(20, (day1.sliderScore || 0) * 2);
    connectionScoreContribution += sliderPts;

    // Checkpoint B: Vibe Check (Game 05) descriptive tile
    if (day1.vibe_d1_category === 'positive') {
      // Positive/Warm: Growing, Hopeful, Energised, Passionate
      connectionScoreContribution += 10;
    } else if (day1.vibe_d1_category === 'tender') {
      // Calm/Tender: Tender, Quiet
      connectionScoreContribution += 7;
    } else if (day1.vibe_d1_category === 'heavy') {
      // Heavy/Challenged: Tired, Drifting
      connectionScoreContribution += 3;
    }

    // ─────────────────────────────────────────────────────────────
    // 2. Dedication Score Contribution (PRD §5.4)
    // ─────────────────────────────────────────────────────────────
    
    // Day 1 fully complete = +1.0 Dedication points
    if (day1.complete) {
      dedicationPointsEarned += 1.0;
    }

    // ─────────────────────────────────────────────────────────────
    // 3. Badge Axis Signals (PRD §7.2 & Day 1 Table)
    // ─────────────────────────────────────────────────────────────
    const answers = day1.quizAnswers || {};

    // ── Axis A: Expressive vs Active ──
    // Quiz Q1: A = Expressive (+2), B = Active (+2) - Primary Axis A signal & tie-breaker
    if (answers['q1'] === 'A') axisASignals.expressive += 2;
    if (answers['q1'] === 'B') axisASignals.active += 2;

    // Quiz Q6: A = Expressive (+2), B = Active (+2)
    if (answers['q6'] === 'A') axisASignals.expressive += 2;
    if (answers['q6'] === 'B') axisASignals.active += 2;

    // Vibe category: Tender/Quiet = Expressive (+1), Active/Energised/Growing = Active (+1)
    if (day1.vibe_d1_category === 'tender') axisASignals.expressive += 1;
    if (day1.vibe_d1_category === 'positive') axisASignals.active += 1;


    // ── Axis B: Deep vs Present ──
    // Quiz Q4: B = Deep (+2), A = Present (+2)
    if (answers['q4'] === 'B') axisBSignals.deep += 2;
    if (answers['q4'] === 'A') axisBSignals.present += 2;

    // Quiz Q7: B = Deep (+2), A = Present (+2) - Primary Axis B signal & tie-breaker
    if (answers['q7'] === 'B') axisBSignals.deep += 2;
    if (answers['q7'] === 'A') axisBSignals.present += 2;


    // ── Axis C: Protecting vs Building ──
    // Day 1 slider baseline: >= 6 = Protecting (+2), <= 5 = Building (+2) - Primary Axis C signal & tie-breaker
    if (day1.sliderScore >= 6) {
      axisCSignals.protecting += 2;
    } else if (day1.sliderScore > 0 && day1.sliderScore <= 5) {
      axisCSignals.building += 2;
    }

    // Quiz Q5: B = Protecting (+1), A = Building (+1)
    if (answers['q5'] === 'B') axisCSignals.protecting += 1;
    if (answers['q5'] === 'A') axisCSignals.building += 1;

    // Quiz Q6: A = Protecting (+1), B = Building (+1)
    if (answers['q6'] === 'A') axisCSignals.protecting += 1;
    if (answers['q6'] === 'B') axisCSignals.building += 1;

    // Quiz Q7: B = Protecting (+1) (if present and chosen B, else A = Building +1)
    if (answers['q7'] === 'B') axisCSignals.protecting += 1;
    if (answers['q7'] === 'A') axisCSignals.building += 1;

    // Vibe Category: Tender/Quiet = Protecting (+1), Energised/Growing/Hopeful = Building (+1)
    if (day1.vibe_d1_category === 'tender') axisCSignals.protecting += 1;
    if (day1.vibe_d1_category === 'positive') axisCSignals.building += 1;

    return {
      connectionScoreContribution,
      dedicationPointsEarned,
      axisASignals,
      axisBSignals,
      axisCSignals,
    };
  },
};
