import { Day2Data, ThisOrThatRound } from '../../store/useDayStore';
import { thisOrThatSets } from '../../data/thisOrThatData';

/**
 * Interface representing the scoring outputs generated by Day 2.
 */
export interface Day2ScoringResult {
  connectionScoreContribution: number; // Mood score normalized (connected/loved/playful=10, grateful/missed=6, heavy=3)
  dedicationPointsEarned: number;        // Complete = +1.0
  axisASignals: {
    expressive: number;
    active: number;
  };
  axisBSignals: {
    deep: number;
    present: number;
  };
  axisCSignals: {
    protecting: number;
    building: number;
  };
}

/**
 * Day 2 Scoring & Logic Engine
 * Processes Day 2 user answers (Mood candle choice, journal entries, and Game 06 predictions)
 * to output precise scoring parameters and badge axis signals.
 */
export const Day2Scoring = {
  /**
   * Helper to analyze "This or That: Us Edition" (Game 06) rounds.
   * Option A (first option) leans comfort/home (Expressive signal).
   * Option B (second option) leans adventure/active (Active signal).
   * Predictions match means they predict their partner is aligned with them (Protecting signal).
   * Predictions differ completely means they anticipate differences (Building signal).
   */
  analyzeThisOrThat: (day2: Day2Data) => {
    let optionBCount = 0;
    let optionACount = 0;
    let predictionMatches = 0;

    const rounds = day2.b2_tot_rounds || [];
    
    // Find all questions across all intention sets to map picks
    const allQuestionsMap = new Map<string, { optionA: string; optionB: string }>();
    (Object.values(thisOrThatSets) as any[]).forEach((set) => {
      set.questions.forEach((q: any) => {
        if (q.options[0] && q.options[1]) {
          allQuestionsMap.set(q.prompt, {
            optionA: q.options[0].text,
            optionB: q.options[1].text,
          });
        }
      });
    });

    rounds.forEach((round: ThisOrThatRound) => {
      // 1. Analyze if choice is Active (Option B) vs Comfort (Option A)
      // Check by text match in options
      let foundType: 'A' | 'B' | null = null;
      for (const [_, options] of allQuestionsMap.entries()) {
        if (options.optionA === round.my_pick) {
          foundType = 'A';
          break;
        }
        if (options.optionB === round.my_pick) {
          foundType = 'B';
          break;
        }
      }

      // Default fallback if text matching is loose
      if (foundType === 'B') {
        optionBCount++;
      } else if (foundType === 'A') {
        optionACount++;
      } else {
        // Fallback guess: emoji/text heuristics
        if (
          round.my_pick.includes('🚶') || 
          round.my_pick.includes('🛠️') || 
          round.my_pick.includes('🎢') || 
          round.my_pick.includes('🗣️') ||
          round.my_pick.includes('💬') ||
          round.my_pick.includes('🚀')
        ) {
          optionBCount++;
        } else {
          optionACount++;
        }
      }

      // 2. Analyze predicted alignment
      if (round.my_pred_of_partner === round.my_pick) {
        predictionMatches++;
      }
    });

    return {
      isAdventureHeavy: optionBCount >= 2,
      isComfortHeavy: optionACount >= 2,
      predictionMatches,
    };
  },

  /**
   * Calculates the full scoring breakdown for Day 2 based on the store's Day 2 data.
   * 
   * @param day2 The stored data for Day 2
   * @returns Day2ScoringResult containing contributions for Connection, Dedication, and the 3 Badge Axes.
   */
  calculate: (day2: Day2Data): Day2ScoringResult => {
    let connectionScoreContribution = 0;
    let dedicationPointsEarned = 0;

    const axisASignals = { expressive: 0, active: 0 };
    const axisBSignals = { deep: 0, present: 0 };
    const axisCSignals = { protecting: 0, building: 0 };

    // ─────────────────────────────────────────────────────────────
    // 1. Connection Score Contribution (PRD §5.1 & §5.2)
    // ─────────────────────────────────────────────────────────────
    
    // Normalise Candle Mood Score:
    // Connected / Loved / Playful = 10 pts
    // Grateful / Missed = 6 pts
    // Overwhelmed / Frustrated / Distant = 3 pts
    const mood = day2.mood;
    if (mood === 'connected' || mood === 'loved' || mood === 'playful') {
      connectionScoreContribution += 10;
    } else if (mood === 'grateful' || mood === 'missed') {
      connectionScoreContribution += 6;
    } else if (mood === 'overwhelmed' || mood === 'frustrated' || mood === 'distant') {
      connectionScoreContribution += 3;
    }

    // ─────────────────────────────────────────────────────────────
    // 2. Dedication Score Contribution (PRD §5.4)
    // ─────────────────────────────────────────────────────────────
    
    // Day 2 complete (mood candle + follow-up completed, not skipped) = +1.0 Dedication points
    if (day2.complete) {
      dedicationPointsEarned += 1.0;
    }

    // ─────────────────────────────────────────────────────────────
    // 3. Badge Axis Signals (PRD §7.2 & Day 2 Table)
    // ─────────────────────────────────────────────────────────────
    
    // ── Axis A: Expressive vs Active ──
    
    // Follow-up Answer: Length >= 60 characters = Expressive (+2)
    if ((day2.followUpAnswer || '').trim().length >= 60) {
      axisASignals.expressive += 2;
    }
    
    // One Good Thing: Length >= 40 characters = Expressive (+1)
    if ((day2.oneGoodThing || '').trim().length >= 40) {
      axisASignals.expressive += 1;
    }

    // Mood connected or playful = Active (+1)
    if (mood === 'connected' || mood === 'playful') {
      axisASignals.active += 1;
    }

    // Game 06 This or That picks analysis
    if (day2.b2_tot_complete) {
      const totAnalysis = Day2Scoring.analyzeThisOrThat(day2);
      
      // 2+ adventure picks = Active (+1)
      if (totAnalysis.isAdventureHeavy) {
        axisASignals.active += 1;
      }
      // 2+ comfort/home picks = Expressive (+1)
      if (totAnalysis.isComfortHeavy) {
        axisASignals.expressive += 1;
      }

      // Predictions match picks 2+ times = Protecting (+1) (Axis C)
      if (totAnalysis.predictionMatches >= 2) {
        axisCSignals.protecting += 1;
      }
      // Predictions differ in all 3 rounds = Building (+1) (Axis C)
      if (totAnalysis.predictionMatches === 0) {
        axisCSignals.building += 1;
      }
    }


    // ── Axis B: Deep vs Present ──
    
    // Mood: loved, grateful, missed = Deep (+1)
    if (mood === 'loved' || mood === 'grateful' || mood === 'missed') {
      axisBSignals.deep += 1;
    }

    // Mood: connected, playful = Present (+1)
    if (mood === 'connected' || mood === 'playful') {
      axisBSignals.present += 1;
    }


    // ── Axis C: Protecting vs Building ──
    
    // Mood: grateful, loved = Protecting (+1)
    if (mood === 'grateful' || mood === 'loved') {
      axisCSignals.protecting += 1;
    }

    // Mood: overwhelmed, frustrated, distant = Building (+1)
    if (mood === 'overwhelmed' || mood === 'frustrated' || mood === 'distant') {
      axisCSignals.building += 1;
    }

    return {
      connectionScoreContribution,
      dedicationPointsEarned,
      axisASignals,
      axisBSignals,
      axisCSignals,
    };
  },
};
