import { Day3Data } from '../../store/useDayStore';

/**
 * Interface representing the scoring outputs generated by Day 3.
 */
export interface Day3ScoringResult {
  connectionScoreContribution: number; // Mirror Game TRUE count (up to 10) + Mood Board warm tiles (up to 10)
  dedicationPointsEarned: number;        // Appreciation Snap (+0.5) + FMS (+0.5) + Mood Board (+0.5) + One Certainty (+0.5)
  axisASignals: {
    expressive: number;
    active: number;
  };
  axisBSignals: {
    deep: number;
    present: number;
  };
  axisCSignals: {
    protecting: number;
    building: number;
  };
}

/**
 * Day 3 Scoring & Logic Engine
 * Processes Day 3 user answers (Appreciation snap, Game 02 Finish My Sentence, 
 * Mirror Game 10 T/F statements, Game 07 Mood Board Match, and the One Certainty)
 * to output precise scoring parameters and badge axis signals.
 */
export const Day3Scoring = {
  /**
   * Hidden tags dictionary for Mood Board Match (Game 07) tiles.
   * Maps each tile ID to Axis A (Expressive/Active), Axis B (Deep/Present), 
   * Axis C (Protecting/Building), and a general Warmth flag (Present/Protecting).
   */
  MOOD_BOARD_TAGS: {
    protected: { axisA: 'expressive', axisB: 'deep', axisC: 'protecting', isWarm: true },
    grounded:  { axisA: 'active',     axisB: 'deep', axisC: 'protecting', isWarm: true },
    valued:    { axisA: 'expressive', axisB: 'deep', axisC: 'protecting', isWarm: true },
    fluid:     { axisA: 'expressive', axisB: 'present', axisC: 'protecting', isWarm: true },
    light:     { axisA: 'expressive', axisB: 'present', axisC: 'protecting', isWarm: true },
    natural:   { axisA: 'active',     axisB: 'present', axisC: 'building',   isWarm: false },
    inspired:  { axisA: 'active',     axisB: 'present', axisC: 'building',   isWarm: false },
    alive:     { axisA: 'active',     axisB: 'present', axisC: 'building',   isWarm: false }
  } as Record<string, { axisA: 'expressive' | 'active'; axisB: 'deep' | 'present'; axisC: 'protecting' | 'building'; isWarm: boolean }>,

  /**
   * Calculates the full scoring breakdown for Day 3 based on the store's Day 3 data.
   * 
   * @param day3 The stored data for Day 3
   * @returns Day3ScoringResult containing contributions for Connection, Dedication, and the 3 Badge Axes.
   */
  calculate: (day3: Day3Data): Day3ScoringResult => {
    let connectionScoreContribution = 0;
    let dedicationPointsEarned = 0;

    const axisASignals = { expressive: 0, active: 0 };
    const axisBSignals = { deep: 0, present: 0 };
    const axisCSignals = { protecting: 0, building: 0 };

    // ─────────────────────────────────────────────────────────────
    // 1. Connection Score Contribution (PRD §5.1 & §5.2)
    // ─────────────────────────────────────────────────────────────
    
    // Checkpoint A: Mirror Game TRUE count (1 pt per TRUE answer, max 10 pts)
    const mirrorAnswers = day3.mirrorAnswers || {};
    const trueCount = Object.values(mirrorAnswers).filter(val => val === true).length;
    connectionScoreContribution += trueCount;

    // Checkpoint B: Mood Board Match (Game 07)
    // Count of warm tiles (Present or Protecting) ÷ 3 × 10 (max 10 pts)
    const selectedTiles = day3.d3_mood_board || [];
    let warmCount = 0;
    selectedTiles.forEach((tileId: string) => {
      const tags = Day3Scoring.MOOD_BOARD_TAGS[tileId];
      if (tags && tags.isWarm) {
        warmCount++;
      }
    });
    
    // Scale to 10 points
    const moodBoardContribution = selectedTiles.length > 0 ? (warmCount / 3) * 10 : 0;
    connectionScoreContribution += moodBoardContribution;

    // ─────────────────────────────────────────────────────────────
    // 2. Dedication Score Contribution (PRD §5.4)
    // ─────────────────────────────────────────────────────────────
    
    // D3 sub-activities:
    // Appreciation Snap completed = +0.5 pts
    if (day3.appreciationSnap && day3.appreciationSnap.trim().length > 0) {
      dedicationPointsEarned += 0.5;
    }
    
    // Finish My Sentence completed = +0.5 pts
    if (day3.d3_fms_pick && day3.d3_fms_pick.trim().length > 0) {
      dedicationPointsEarned += 0.5;
    }
    
    // Mood Board Match completed (exactly 3 selected) = +0.5 pts
    if (selectedTiles.length === 3) {
      dedicationPointsEarned += 0.5;
    }
    
    // One Certainty completed = +0.5 pts
    if (day3.oneCertainty && day3.oneCertainty.trim().length > 0) {
      dedicationPointsEarned += 0.5;
    }

    // ─────────────────────────────────────────────────────────────
    // 3. Badge Axis Signals (PRD §7.2 & Day 3 Table)
    // ─────────────────────────────────────────────────────────────
    
    // ── Checkpoint A: Mirror Game T/F Statements ──
    // 7 to 10 TRUE answers = Deep (+2) & Protecting (+1)
    // 0 to 4 TRUE answers = Present (+2)
    if (trueCount >= 7) {
      axisBSignals.deep += 2;
      axisCSignals.protecting += 1;
    } else if (trueCount >= 0 && trueCount <= 4 && Object.keys(mirrorAnswers).length > 0) {
      axisBSignals.present += 2;
    }

    // ── Checkpoint B: Finish My Sentence (Game 02) Tag ──
    const fmsTag = day3.d3_fms_tag;
    if (fmsTag) {
      // Axis A: Expressive vs Active
      if (fmsTag === 'Expressive' || fmsTag === 'Deep') axisASignals.expressive += 1;
      if (fmsTag === 'Active' || fmsTag === 'Playful') axisASignals.active += 1;

      // Axis B: Deep vs Present
      if (fmsTag === 'Deep' || fmsTag === 'Resilience') axisBSignals.deep += 1;
      if (fmsTag === 'Present' || fmsTag === 'Playful') axisBSignals.present += 1;

      // Axis C: Protecting vs Building
      if (fmsTag === 'Protective') axisCSignals.protecting += 1;
      if (fmsTag === 'Building' || fmsTag === 'Active') axisCSignals.building += 1;
    }

    // ── Checkpoint C: Mood Board Match (Game 07) Tile Majority ──
    if (selectedTiles.length === 3) {
      let axisAMajority = { expressive: 0, active: 0 };
      let axisBMajority = { deep: 0, present: 0 };
      let axisCMajority = { protecting: 0, building: 0 };

      selectedTiles.forEach((tileId: string) => {
        const tags = Day3Scoring.MOOD_BOARD_TAGS[tileId];
        if (tags) {
          axisAMajority[tags.axisA]++;
          axisBMajority[tags.axisB]++;
          axisCMajority[tags.axisC]++;
        }
      });

      // Award +1 point to majority on each axis
      if (axisAMajority.expressive >= 2) axisASignals.expressive += 1;
      else if (axisAMajority.active >= 2) axisASignals.active += 1;

      if (axisBMajority.deep >= 2) axisBSignals.deep += 1;
      else if (axisBMajority.present >= 2) axisBSignals.present += 1;

      if (axisCMajority.protecting >= 2) axisCSignals.protecting += 1;
      else if (axisCMajority.building >= 2) axisCSignals.building += 1;
    }

    return {
      connectionScoreContribution,
      dedicationPointsEarned,
      axisASignals,
      axisBSignals,
      axisCSignals,
    };
  },
};
