import { Day4Data } from '../../store/useDayStore';

/**
 * Interface representing the scoring outputs generated by Day 4.
 */
export interface Day4ScoringResult {
  toneScore: number;                    // NLP-scanned mood score (7 = Warm, 4 = Heavy, 5 = Neutral)
  trendBonusEarned: number;              // Compared to Day 1 slider: Warmer=+10, Same=+5, Lower=0
  dedicationPointsEarned: number;        // Memory Jar (+1) + Tiny Compliment (+0.5) + Shuffle (+0.5) + Daily 2 (+0.25 to +0.5) + Love Drop (+0.5) + Drop Box (+0.5)
  axisASignals: {
    expressive: number;
    active: number;
  };
  axisBSignals: {
    deep: number;
    present: number;
  };
  axisCSignals: {
    protecting: number;
    building: number;
  };
}

/**
 * Day 4 Scoring & Logic Engine
 * Processes Day 4 user answers (Memory Jar, Tiny Compliment, Game 08 Priority Shuffle, 
 * The Daily 2 journal entries, and Game 04 Love Drop / Drop Box tabs)
 * to output precise scoring parameters and badge axis signals.
 */
export const Day4Scoring = {
  /**
   * Simple NLP-style keyword scanner to detect emotional tone in Daily 2 Q1 response.
   * Grateful/happy/calm/loved/good = Warm (7)
   * Tired/frustrated/anxious/distant = Heavy (4)
   * Neutral/fallback = Neutral (5)
   */
  scanTone: (text: string): number => {
    const cleanText = (text || '').toLowerCase().trim();
    if (!cleanText) return 5; // Default neutral if empty

    const warmKeywords = [
      'grateful', 'happy', 'calm', 'loved', 'good', 'thankful', 
      'peaceful', 'joyful', 'content', 'connected', 'excited',
      'warm', 'blessed', 'optimistic', 'hopeful', 'satisfied'
    ];
    const heavyKeywords = [
      'tired', 'frustrated', 'anxious', 'distant', 'heavy', 'sad', 
      'stressed', 'lonely', 'angry', 'hurt', 'routine', 'drift',
      'exhausted', 'overwhelmed', 'worried', 'scared', 'cold', 'disconnected'
    ];

    let warmMatches = 0;
    let heavyMatches = 0;

    warmKeywords.forEach(kw => {
      if (cleanText.includes(kw)) warmMatches++;
    });

    heavyKeywords.forEach(kw => {
      if (cleanText.includes(kw)) heavyMatches++;
    });

    if (warmMatches > heavyMatches) return 7; // Warm tone
    if (heavyMatches > warmMatches) return 4; // Heavy tone
    return 5; // Neutral tone (including equal ties or no matches)
  },

  /**
   * Compares the scanned Day 4 mood tone to the Day 1 slider score baseline
   * to determine the Trend Bonus.
   * 
   * @param day1Slider Day 1 slider score (1-10)
   * @param d4Tone Day 4 scanned tone score (4, 5, or 7)
   * @returns Trend Bonus point contribution (+10, +5, or 0)
   */
  calculateTrendBonus: (day1Slider: number, d4Tone: number): number => {
    // Categorize baseline slider:
    // Low: <= 4, Medium: 5-7, High: >= 8
    const baseline = day1Slider || 5; // Fallback to 5 if undefined

    if (baseline >= 8) {
      // Started High:
      // Tone 7 (Warm) = Same (+5)
      // Tone 5 (Neutral) = Lower (0)
      // Tone 4 (Heavy) = Lower (0)
      return d4Tone === 7 ? 5 : 0;
    } else if (baseline >= 5) {
      // Started Medium:
      // Tone 7 (Warm) = Warmer (+10)
      // Tone 5 (Neutral) = Same (+5)
      // Tone 4 (Heavy) = Lower (0)
      if (d4Tone === 7) return 10;
      if (d4Tone === 5) return 5;
      return 0;
    } else {
      // Started Low:
      // Tone 7 (Warm) = Warmer (+10)
      // Tone 5 (Neutral) = Warmer (+10)
      // Tone 4 (Heavy) = Same (+5)
      if (d4Tone === 7 || d4Tone === 5) return 10;
      return 5;
    }
  },

  /**
   * Calculates the full scoring breakdown for Day 4 based on the store's Day 4 data and Day 1's baseline.
   * 
   * @param day4 The stored data for Day 4
   * @param day1Slider Day 1 baseline slider score (passed from Day 1 data)
   * @returns Day4ScoringResult containing contributions for Connection, Dedication, and the 3 Badge Axes.
   */
  calculate: (day4: Day4Data, day1Slider: number): Day4ScoringResult => {
    const axisASignals = { expressive: 0, active: 0 };
    const axisBSignals = { deep: 0, present: 0 };
    const axisCSignals = { protecting: 0, building: 0 };

    // ─────────────────────────────────────────────────────────────
    // 1. Connection Score Contribution (NLP Scan & Trend Bonus)
    // ─────────────────────────────────────────────────────────────
    const toneScore = Day4Scoring.scanTone(day4.daily2Q1);
    const trendBonusEarned = Day4Scoring.calculateTrendBonus(day1Slider, toneScore);

    // ─────────────────────────────────────────────────────────────
    // 2. Dedication Score Contribution (PRD §5.4)
    // ─────────────────────────────────────────────────────────────
    let dedicationPointsEarned = 0;

    // Memory Jar used (Text, Photo, Emoji) = +1.0 Dedication points (Highest single Day 4 task)
    if (day4.memoryType !== 'skipped' && day4.complete) {
      dedicationPointsEarned += 1.0;
    }

    // Tiny Compliment completed = +0.5 Dedication points
    if (day4.tinyComplimentWord && day4.tinyComplimentWord.trim().length > 0) {
      dedicationPointsEarned += 0.5;
    }

    // Priority Shuffle (Game 08) completed (3 ranked items) = +0.5 Dedication points
    if (day4.d4_priority_picks && day4.d4_priority_picks.length === 3) {
      dedicationPointsEarned += 0.5;
    }

    // Daily 2: Both answered = +0.5; One answered = +0.25
    if (day4.daily2Status === 'both') {
      dedicationPointsEarned += 0.5;
    } else if (day4.daily2Status === 'one') {
      dedicationPointsEarned += 0.25;
    }

    // Love Drop used = +0.5 Dedication points
    if (day4.loveDropUsed) {
      dedicationPointsEarned += 0.5;
    }

    // Drop Box used = +0.5 Dedication points
    if (day4.dropBoxUsed) {
      dedicationPointsEarned += 0.5;
    }

    // ─────────────────────────────────────────────────────────────
    // 3. Badge Axis Signals (PRD §7.2 & Day 4 Table)
    // ─────────────────────────────────────────────────────────────

    // ── Checkpoint A: The Memory Jar ──
    // Text Memory = Expressive +2
    // Photo Memory = Active +2
    // Emoji Memory = Active +1
    if (day4.memoryType === 'text') {
      axisASignals.expressive += 2;
    } else if (day4.memoryType === 'photo') {
      axisASignals.active += 2;
    } else if (day4.memoryType === 'emoji') {
      axisASignals.active += 1;
    }

    // ── Checkpoint B: The Daily 2 answers length ──
    // Both answered with 40+ characters each = Expressive (+1)
    const q1Len = (day4.daily2Q1 || '').trim().length;
    const q2Len = (day4.daily2Q2 || '').trim().length;
    if (q1Len >= 40 && q2Len >= 40) {
      axisASignals.expressive += 1;
    }

    // ── Checkpoint C: Priority Shuffle (Game 08) ──
    // Cards keywords lookup:
    // warmth: "More warmth & affection"
    // time: "Dedicated time together"
    // calm: "More calm, less stress"
    // laughter: "Laughter & lightness"
    // conversations: "Deeper conversations"
    const picks = day4.d4_priority_picks || [];
    const topNeed = day4.d4_top_need;

    if (picks.length === 3) {
      // 1. conversations ("Deeper conversations") in top 3 = Deep (+2)
      if (picks.includes('conversations') || picks.includes('Deeper conversations')) {
        axisBSignals.deep += 2;
      }
      
      // 2. calm ("More calm, less stress") in top 3 = Deep (+1)
      if (picks.includes('calm') || picks.includes('More calm, less stress')) {
        axisBSignals.deep += 1;
      }

      // 3. laughter ("Laughter & lightness") as Rank 1 = Present (+2)
      if (topNeed === 'laughter' || topNeed === 'Laughter & lightness') {
        axisBSignals.present += 2;
      }

      // 4. Rank 1 Warmth or Calm = Protecting (+2)
      if (
        topNeed === 'warmth' || topNeed === 'More warmth & affection' ||
        topNeed === 'calm' || topNeed === 'More calm, less stress'
      ) {
        axisCSignals.protecting += 2;
      }

      // 5. Rank 1 Laughter, Time, or Conversations = Building (+2)
      if (
        topNeed === 'laughter' || topNeed === 'Laughter & lightness' ||
        topNeed === 'time' || topNeed === 'Dedicated time together' ||
        topNeed === 'conversations' || topNeed === 'Deeper conversations'
      ) {
        axisCSignals.building += 2;
      }
    }

    // ── Checkpoint D: Love Drop (Tab A) ──
    if (day4.loveDropUsed && day4.loveDropType) {
      // Any use = Deep +1
      axisBSignals.deep += 1;

      // Type is Compliment = Expressive (+1) & Protecting (+1)
      // Type is Memory = Protecting (+1)
      // Type is Challenge = Building (+1)
      if (day4.loveDropType === 'compliment') {
        axisASignals.expressive += 1;
        axisCSignals.protecting += 1;
      } else if (day4.loveDropType === 'memory') {
        axisCSignals.protecting += 1;
      } else if (day4.loveDropType === 'challenge') {
        axisCSignals.building += 1;
      }
    }

    // ── Checkpoint E: Drop Box (Tab B) ──
    if (day4.dropBoxUsed) {
      // Used at all = Deep (+2) & Building (+1) (highest Deep signal in app)
      axisBSignals.deep += 2;
      axisCSignals.building += 1;
    }

    return {
      toneScore,
      trendBonusEarned,
      dedicationPointsEarned,
      axisASignals,
      axisBSignals,
      axisCSignals,
    };
  },
};
